### ISSUE TITLE
Support nes subscriptions

### ISSUE THREAD

**Issue by devinivy** [hapipal/haute-couture#26]
https://github.com/hapijs/nes/blob/master/API.md#serversubscriptionpath-options

**Comment by nagyv** [comment]
Hi!

I have a working Nes integration with Hapipal using schmervice and an EventEmitter. How could I help you?

**Comment by nagyv** [comment]
I've put together a simple gist to demonstrate this:

https://gist.github.com/nagyv/9286a27dfd424bd155553a36e33abaa6

2018-06-03 20:23 GMT+02:00 devin ivy <notifications@github.com>:

**Comment by optii** [comment]
Hi, 

wondering if i can get something put together for this ? Is there anything to look out for or is it basically adding the mapping to the manifest ?

**Comment by devinivy** [comment]
Nothing too tricky if you're already familiar with the manifest.  It's adding it to the manifest, writing the relevant tests, and adding documentation.

**Comment by devinivy** [comment]
Resolved by #51 and released in v3.3.0.  Thanks @optii!
