### ISSUE TITLE
Load cache configurations before plugins

### ISSUE THREAD

**Issue by michaelhue** [hapipal/haute-couture#38]
## Problem
Some plugins like [yar](https://github.com/hapijs/yar) access the cache while registering. Cache configurations are registered _after_ plugins and are not available to plugins.

## Workaround
Provision caches in the `register` function of the main `lib/index.js` plugin, before calling `HauteCouture.using()`.

## Proposed solutions
- Register caches before plugins if possible.
- Allow user to change the registration order.

I can provide a pull request if you like. Wanted to make sure I didn't miss something by discussing it first.

P.S. Thanks for creating this suite of tools, cleared up some insecurities I had about Hapi.

**Comment by devinivy** [comment]
> Allow user to change the registration order.

That's currently possible using [amendments](https://github.com/hapipal/haute-couture/blob/master/API.md#hautecoutureusingdirname-amendments), but feel free to offer any suggestions to make that simpler.  Maybe some day we could add a `modify` option (in addition to `add` and `remove`).

> Register caches before plugins if possible.

I think this is the solution we're looking for!

Sounds good to me—go for it.  Thanks for the nice issue writeup!  And cheers 🍻 very glad to make folks feel more comfortable about their choice to use hapi.

**Comment by devinivy** [comment]
3.0.1 is released 👌thanks again, @michaelhue.
