### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by jeff-kilbride** [hapipal/haute-couture#40]
Hi Guys!

I'm finally getting around to porting an api from `hapi` v16 to v17. I'm also looking at running it from AWS Lambda, so I'm trying to minimize the dependencies. With that in mind, I wanted to get rid of `glue` and `confidence`, and use `haute-couture` to wire everything from plugins. However, I was having some initial confusion structuring the plugin implementations vs. the `plugins` directory that `haute-couture` scans for it's config info.

After banging my head for a while, I took a step back and implemented a simple example using a mix of the sample code from the `hapi` site and your repo. That cleared things up for me and helped a lot. I didn't want it to go to waste, so I uploaded it to my github account. Please feel free to copy it and use it as an example in your repo, if you'd like.

https://github.com/jeff-kilbride/haute-couture-example

Thanks for all the amazing work! I'm looking forward to trying out `schwifty` next.

**Comment by devinivy** [comment]
This is awesome, @jeff-kilbride!  Really appreciate that you captured that into a repo for others to reference.  I featured it in a hapi pal update https://medium.com/@hapipal/the-hapi-pal-roadmap-build-a-healthy-community-around-building-healthy-nodejs-web-services-820c66d978c0 🎊 

I will think about how it might fit into the examples repo.  I realize it's somewhat superficial, but I wonder if having a consistent code style in the examples is important to reduce noise for newcomers.  I expect we'll find a good place for it, one way or another!

**Comment by jeff-kilbride** [comment]
@devinivy  Yeah, sorry, I didn't even realize you guys had a `boilerplate` repo or `hapipal` website. I found those shortly after posting this example.  😄  I don't think there's a link to either in the `haute-couture` readme.  The `boilerplate` is pretty close to my normal setup with `glue` and `confidence`.

Thanks for the mention!

**Comment by devinivy** [comment]
It took a little while, but I think found a good place :) https://github.com/hapipal/examples

Thanks again, @jeff-kilbride!
