### ISSUE TITLE
`request.models()` is undefined in handler of third party plugin

### ISSUE THREAD

**Issue by ozum** [hapipal/haute-couture#46]
I'm using haute-couture, schwifty with [hapi-openapi](https://github.com/krakenjs/hapi-openapi) plugin, which provides routes based on OpenAPI (Swagger) definition file automatically.

`request.models()` returns `{}` in `hapi-openapi` handlers.

For testing purposes I also created `lib/decorations/request.test.js` request decoration method:

|Where|`request.test()`|`request.models()`|`request.models`|
|---|:---:|:---:|:---:|
|in **haute-couture** handlers|✔️|✔️|`function`|
|in **hapi-openapi** handlers|✔️|`{}`|`function`|

I thought that it could be related to runtime order of plugins, but considering `request.test()` is available, it seems unlikely.

Any suggestions may help,

Thanks,

**Comment by devinivy** [comment]
Just making sure I understand the issue— is it `request.models` or `request.models()` that is `undefined`?  Can you also share your version of schwifty and haute-couture?

**Comment by ozum** [comment]
schwifty 4.0.0
haute-couture 3.0.1

Sorry, a mistake in my first post: `request.models()` returns `{}` not `undefined`.

`request.models` is a function, so request seems decorated.

I updated my first post accordingly:

|Where|`request.test()`|`request.models()`|`request.models`|
|---|:---:|:---:|:---:|
|in **haute-couture** handlers|✔️|✔️|`function`|
|in **hapi-openapi** handlers|✔️|`{}`|`function`|

**Comment by optii** [comment]
Have you tried with `request.models(true)` ? Schwifty has a realm so models aren't shared across plugins by default

**Comment by ozum** [comment]
Oh, I missed that @optil.

Thanks everybody.

**Comment by devinivy** [comment]
Yeah, that's it!  There's a description of this behavior here.  https://github.com/hapipal/schwifty/blob/master/API.md#plugin-ownership-of-knex-instances-and-models  The goal is to make plugin boundaries very clear :)
