### ISSUE TITLE
Depercated `mode` property in authentication strategy documentation

### ISSUE THREAD

**Issue by tmbarkve** [hapipal/haute-couture#48]
The `API.md` indicates that the `auth/strategies.js` should "export an array of objects `{ name, scheme, mode, options }` or function(server, options) that returns an array of objects." whereas the `mode` property seem to have been removed from hapi in v.17 (https://github.com/hapijs/hapi/issues/3612). 

The internal manifest in haute-couture doesn't seem to mind the `mode` as well: 
```js
{
        place: 'auth/strategies',
        method: 'auth.strategy',
        signature: ['name', 'scheme', '[options]'],
        list: true,
        useFilename: internals.passthruOn('name'),
        after: ['auth/schemes', 'plugins'],
        example: {
            name: '',
            scheme: '',
            options: { $value: {}, $comment: 'Optional' }
        }
}
```

**Comment by devinivy** [comment]
Resolved in https://github.com/hapipal/haute-couture/pull/49
