### ISSUE TITLE
How to register second database instance with schwifty?

### ISSUE THREAD

**Issue by enkot** [hapipal/haute-couture#54]
Thx for great library!) I'd like to connect 2nd database, what is the proper way to register second knex instance and use with schwifty models?

**Comment by devinivy** [comment]
Cheers!  So, schwifty will manage one knex instance for you per hapi plugin, as described here: https://github.com/hapipal/schwifty/blob/master/API.md#plugin-ownership-of-knex-instances-and-models

With haute-couture you can define a knex instance within a plugin by registering schwifty inside that plugin and configuring schwifty with some knex options.  It might look like this,
```js
// my-app/plugins/schwifty.js
'use strict';

module.exports = (server, options) => ({
    plugins: {
        // When registering my-app-1 as a plugin, just pass it a knex instance
        options: { knex: options.knex }
    }
});
```

Now any models defined under `my-app-1/` will use whatever knex instance was passed as a plugin option to my-app-1 when it is registered.  You can do the same in `my-app-2`, and schwifty will ensure that the models in each of the plugins use the correct knex instances.

If you need to have _a single_ plugin that utilizes multiple knex instances, then the solution is to simply not tell schwifty about knex at all, and bind knex to your models manually, likely during hapi's `onPreStart` (which is how schwifty does it).

**Comment by enkot** [comment]
Thank you for instant feedback! I have just implemented option with multiple plugins:)

**Comment by devinivy** [comment]
Excellent! 🎉
