### ISSUE TITLE
Proposing API updates for v4

### ISSUE THREAD

**Issue by devinivy** [hapipal/haute-couture#65]
I started digging into the question: assuming that breaking changes are allowed, how can we improve the haute-couture API?  Here's what I came-up with.  I will illustrate all the changes through examples:

Here I'm working to **avoid the awkward double function call `using()(server, options)`** to compose the plugin and utilize **more descriptive method naming**, which also happens to be **consistent with glue**:

```js
// Plugin with room for custom code.
// This is an important example because it will be used by default in the boilerplate.

exports.plugin = {
    name: 'my-plugin',
    register: async (server, options) => {

        // Custom plugin code can go here

        await HauteCouture.compose(server, options);
    }
};
```

This leads us to ask: how would one specify `dirname` and `amendments`?  I propose these be added in a single configuration object as the last, optional arg to `compose()` providing **simpler application of defaults** and **easier to understand by giving the configuration options names** rather than making them floating, independent args:

```js
await HauteCouture.compose(server, options, { dirname, amendments });
```

For plugins that are fully-composed by haute-couture without any custom code but need to set these options, I propose **a helper providing the same convenience for which `using()` is currently optimized**:

```js
exports.plugin = {
    name: 'my-plugin',
    register: HauteCouture.composeWith({ dirname, amendments })
};
```

Notice that if you're not using any special configuration it's even simpler and you don't need the helper:

```js
exports.plugin = {
    name: 'my-plugin',
    register: HauteCouture.compose
};
```

Now digging into the system for amendments.  I never really loved working with amendments because the `{ add, remove, ...defaults }` API is a little awkward, and it's not actually straightforward to _modify_ a manifest item, e.g. to set `recursive` for a single item: you need to create a default manifest with `includeExtras`, find the item with the `place` you're overriding, then use that to build a new, complete amendment manifest item.  We can **model away some of these problems by recognizing that `place` is unique**.  I propose amendments be specified as a `place`-keyed object and that we introduce a new interface for getting the base amendments, **separating manifest from amendments logically and in data** rather than mixing them together, particularly in `manifest.create()`'s `includeExtras`:

```js
await HauteCouture.compose(server, options, {
    amendments: {
        // Disable use of auth/default.js
        'auth/default': false,
        // Create nes subscriptions in the subscriptions/ directory
        subscriptions: {
            list: true,
            method: 'subscription',
            signature: ['path', 'options']
        }
    }
});
```

I propose that **setting defaults work the same as configuring any other amendment** by using a special key name `$defaults` similar to confidence's directive naming:

```js
await HauteCouture.compose(server, options, {
    amendments: {
        $defaults: {
            recursive: true
        }
    }
});
```

In the case that the user wants to use a directory named `$defaults` we can cater to that with a symbol, making non-symbol usage `$defaults` technically just for convenience:

```js
await HauteCouture.compose(server, options, {
    amendments: {
        [HauteCouture.defaults]: {
            recursive: true
        },
        $defaults: {
            method: 'setPrivateDefaults', // Suppose this is provided by a third-party plugin
        }
    }
});
```

Introducing an interface for looking-up base amendments makes **modifying an item through an amendment more natural**:

```js
await HauteCouture.compose(server, options, {
    amendments: {
        // Built using spread:
        models: {
            ...HauteCouture.amendment('models'),
            recursive: true
        },
        // Or built with a second argument for convenience:
        services: HauteCouture.amendment('services', {
            recursive: true
        })
    }
});
```

Finally, you would be able to receive all base amendments (haute-couture's internal default configuration) using `HauteCouture.amendments()` and create an [haute](https://github.com/devinivy/haute) manifest (only tooling that needs to interop such as hpal really cares about this) using `HauteCouture.manifest(amendments)`, which is a more concise than the current API.  Another minor point: the order of amendments' `useFilename()` args will change to `(value, filename, path) => ...` in order to fall back in sync with haute (the args were originally swapped to avoid a breaking change in the past).

I look forward to hearing feedback on these proposals.  We have a little time to figure it out, as breaking changes to haute-couture's peer dependencies (i.e. schwifty and schmervice) should be released prior to these upcoming updates to haute-couture.

**Comment by Nargonath** [comment]
I didn't see this post before but it all looks good to me! Well done @devinivy .

**Comment by devinivy** [comment]
Aw, thanks!  I am glad you think it looks good, as this is published in v4 😏 https://www.npmjs.com/package/@hapipal/haute-couture

I will be merging the v4 branch and making a more prominent release once all modules and the boilerplate are up to date, and some release notes are written.
