### ISSUE TITLE
Default manifest items to follow deeply nested folders

### ISSUE THREAD

**Issue by devinivy** [hapipal/haute-couture#66]
It seems to have become common usage to turn the `recursive` manifest default to `true`, often as a way to use a deeper folder structure to organize routes, cookies, etc.  In v4 let's consider making this the default behavior.

**Comment by wswoodruff** [comment]
👍 I've set this on all my projects FWIW -- mostly for organizing my routes into folders

**Comment by timcosta** [comment]
I almost always create a folder per path segment or entity, and then a file per action that can be taken on that entity. setting recursive to true is the first step i take in every project as well.
