### ISSUE TITLE
Drop support for separate plugin registration options argument in plugins/

### ISSUE THREAD

**Issue by devinivy** [hapipal/haute-couture#67]
The plugins/ items have always been a little bit ugly to work with.  In order to fully support hapi's API [`server.register(plugins, [options])`](http://github.com/hapijs/hapi/blob/master/API.md#server.register()), we usually end-up exporting plugin configs that look like this:

```js
module.exports = {
    plugins: {
        plugin: require('../my-plugin'),
        options: {
            something: true
        }
    },
    // Registrations options go here, but we can also include them above
    options: {
        once: true,
        routes: { prefix: '/' }
    }
};
```

Aside from seeing `plugins` often not contain an array but a single item, the duplicate names "`plugins`" and "`plugin`", and the confusion between registration options versus plugin options, I don't think it's necessarily worth the trouble to support registration `options`.  Note that registration options can already be placed on individual registration items, so the only support we're giving up is _applying registration options once for a list of plugins_.  I am interested to hear if folks commonly want/use this functionality, but I can't think of a time I've ever used that while using haute-couture.

The proposal for v4 is to switch from the v3 mapping `{ plugins, options }` -> `server.register(plugins, [options])` to the mapping `plugins` -> `server.register(plugins)`, dropping support for `options`.  The example above would look like this:

```js
module.exports = {
    plugin: require('../my-plugin'),
    options: {
        something: true
    },
    // Registration options are still supported on individual items
    once: true,
    routes: { prefix: '/' },
};
```

**Comment by mattboutet** [comment]
>applying registration options once for a list of plugins
I've definitely never done this, and I'm having a hard time coming up with a non-contrived case where it'd be useful.

While we're considering breaking things, I still think the ambiguity of:
```js
options: {...},
more: options,
here: true
```
I don't really have an idea I love, but the _thought_ of having pluginOptions and registrationOptions more explicitly separated appeals to me.

That said, I think what's proposed above is a definite improvement in ergonomics, so 👍

**Comment by devinivy** [comment]
Yeah I see what you mean.  I think the key is that we're just supporting hapi's (and glue's) interface for these options, and I wonder if it's beyond our purview to adjust how registration options on individual plugins are specified.  Although making a proposal to hapi might be fruitful, and haute-couture would likely automatically support it since it's a passthrough to hapi's interface.
