### ISSUE TITLE
How to write amendment to change location of schwifty models?

### ISSUE THREAD

**Issue by miccoh1994** [hapipal/haute-couture#81]
Currently I have schwifty models under the default 'models' path. I would like to instead place my models under './db/models/' along with my migratiions and seeds which are stored in './db'. How would I write an amendment to do this?

**Comment by devinivy** [comment]
The idea is to "turn off" the `models` amendment, and add a `db/models` amendment using the contents of the standard `models` amendment.  That will look like this (assuming haute-couture v4):
```js
// lib/.hc.js
'use strict';

const HauteCouture = require('@hapipal/haute-couture');

module.exports = {
    models: false,                                // Turn off models
    'db/models': HauteCouture.amendment('models') // Enable db/models using the standard models setup
};
```

You will also want to configure the migrations directory, which is a plugin option passed to schwifty.  For a complete example you can see this diff against the realworld app: https://github.com/devinivy/hapipal-realworld-example-app/compare/model-amendment-example?expand=1#diff-7780b4d4c3fa1f70aab38854d6b437ddda0a1455812a983c75634d6c4b24eb7f.  The most relevant files in the diff are lib/.hc.js (amendment) and lib/plugins/@hapipal.schwifty.js (migrations directory).

**Comment by miccoh1994** [comment]
Thanks so much @devinivy, this really cleared up my understanding of amendments for places.
